---
title: "What makes up an ideal hockey player"
author: Emilie 
date: 2/22/2026
categories:
  - DOW
  - Hockey 
  - Olympics 
---

# What makes up an ideal hockey player?

![](img/beginning.png){width=800}

Since women's hockey officially became an Olympic sport in 1998, either USA or Canada has won each winter olympics cycle. 

### Olympic Women's Hockey Gold Medal Winners
- **2022** (Beijing): Canada 
- **2018** (Pyeongchang): USA 
- **2014** (Sochi): Canada 
- **2010** (Vancouver): Canada
- **2006** (Torino): Canada 
- **2002** (Salt Lake City): Canada 
- **1998** (Nagano): USA

**This made wonder what makes these two teams so dominant in ice hockey? And are there traits that can make up an ideal hockey player?**

In [4]:
import pandas as pd

In [6]:
medals_df = pd.read_csv('data/winter_olympics_medals.csv')
athletes_df = pd.read_csv('data/bios.csv')

In [21]:
canada_gold = medals_df.query("event == 'Ice Hockey, Women (Olympic)' and team == 'Canada' and medal == 'Gold'")

In [31]:
Canada_players = canada_gold["as"].drop_duplicates()

![](img/canada_flag.png){width=600}

#### **All of Canada's women hockey players that won gold so far:**

In [33]:
Canada_players

34561     Jennifer Botterill
34565        Thérèse Brisson
34567        Cassie Campbell
34572            Lori Dupuis
34574       Danielle Goyette
34577       Geraldine Heaney
34579          Jayna Hefford
34584           Becky Kellar
34595         Vicky Sunohara
34598    Hayley Wickenheiser
39198             Dana Antal
39199          Kelly Béchard
39200     Isabelle Chartrand
39201     Caroline Ouellette
39205           Cherie Piper
39208         Cheryl Pounder
39210     Tammy Lee Shewchuk
39211          Sami Jo Small
39212      Colleen Sostorics
39215          Kim St-Pierre
42317        Gillian Ferrari
42318           Gillian Apps
42321          Carla MacLeod
42325          Meghan Agosta
42329      Katie Weatherston
42330     Sarah Vaillancourt
42332         Gina Kingsbury
42334        Charlie Labonté
47122         Catherine Ward
47174            Haley Irwin
47285    Marie-Philip Poulin
47309      Meaghan Mikkelson
47388       Rebecca Johnston
47432       Shannon Szabados
47447         Tessa Bonhomme
49644         Mélodie Daoust
49647          Laura Fortino
49649         Brianne Jenner
49652      Jocelyne Larocque
49655       Lauriane Rougeau
49657        Natalie Spooner
49660         Jenn Wakefield
49662          Tara Watchorn
54331            Emily Clark
54333     Ann-Renée Desbiens
54335            Renata Fast
54338            Sarah Nurse
54340       Jillian Saulnier
54342           Laura Stacey
54344        Blayre Turnbull
62822           Erin Ambrose
62823            Ashton Bell
62824       Kristen Campbell
62825          Sarah Fillier
62826           Emma Maltais
62827    Emerance Maschmeyer
62828      Jamie Lee Rattray
62829           Ella Shelton
62830        Claire Thompson
62831      Micah Zandee-Hart
Name: as, dtype: str

In [36]:
Canada_bios = athletes_df[athletes_df["name"].isin(Canada_players)]

![](img/canada_ace.png){width=400}

#### **Canada women's hockey players that won gold individual bios:**

In [37]:
Canada_bios

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
99553,100352,Jennifer Botterill,1979-05-01,Ottawa,Ontario,CAN,Canada,175.0,71.0,NaN
99554,100353,Thérèse Brisson,1966-10-05,Montréal,Québec,CAN,Canada,170.0,68.0,NaN
99555,100354,Cassie Campbell,1973-11-22,Richmond Hill,Ontario,CAN,Canada,170.0,66.0,NaN
99558,100357,Lori Dupuis,1972-11-14,Cornwall,Ontario,CAN,Canada,173.0,75.0,NaN
99559,100358,Danielle Goyette,1966-01-30,Saint-Nazaire,Québec,CAN,Canada,168.0,70.0,NaN
99560,100359,Geraldine Heaney,1967-10-01,Lurgan,Northern Ireland,GBR,Canada,173.0,64.0,NaN
99561,100360,Jayna Hefford,1977-05-14,Trenton,Ontario,CAN,Canada,163.0,63.0,NaN
99562,100361,Becky Kellar,1975-01-01,Hagersville,Ontario,CAN,Canada,170.0,71.0,NaN
99570,100369,Vicky Sunohara,1970-05-18,NaN,NaN,NaN,Canada,170.0,75.0,NaN
99571,100370,Hayley Wickenheiser,1978-08-12,Shaunavon,Saskatchewan,CAN,Canada,178.0,77.0,NaN
101207,102076,Dana Antal,1977-04-19,Saskatoon,Saskatchewan,CAN,Canada,170.0,64.0,NaN
101208,102077,Kelly Béchard,1978-01-22,Sedley,Saskatchewan,CAN,Canada,175.0,66.0,NaN
101209,102078,Isabelle Chartrand,1978-04-20,Montréal,Québec,CAN,Canada,165.0,62.0,NaN
101210,102079,Caroline Ouellette,1979-05-25,Montréal,Québec,CAN,Canada,180.0,77.0,NaN
101211,102080,Cherie Piper,1981-06-29,NaN,NaN,NaN,Canada,168.0,76.0,NaN
101212,102081,Cheryl Pounder,1976-06-21,Montréal,Québec,CAN,Canada,165.0,64.0,NaN
101213,102082,Tammy Lee Shewchuk,1977-12-31,Pointe-Claire,Québec,CAN,Canada,163.0,60.0,NaN
101214,102083,Sami Jo Small,1976-03-25,Winnipeg,Manitoba,CAN,Canada,170.0,85.0,NaN
101215,102084,Colleen Sostorics,1979-12-17,Kennedy,Saskatchewan,CAN,Canada,163.0,76.0,NaN
101216,102085,Kim St-Pierre,1978-12-14,Châteauguay,Québec,CAN,Canada,175.0,71.0,NaN
109061,110243,Gillian Ferrari,1980-06-23,Thornhill,Ontario,CAN,Canada,173.0,73.0,NaN
109062,110244,Gillian Apps,1983-11-02,NaN,NaN,NaN,Canada,180.0,80.0,NaN
109063,110245,Carla MacLeod,1982-06-16,Spruce Grove,Alberta,CAN,Canada,163.0,63.0,NaN
109066,110248,Meghan Agosta,1987-02-12,Windsor,Ontario,CAN,Canada,168.0,67.0,NaN
109067,110249,Katie Weatherston,1983-04-06,Thunder Bay,Ontario,CAN,Canada,163.0,66.0,NaN
109068,110250,Sarah Vaillancourt,1985-05-08,Sherbrooke,Québec,CAN,Canada,168.0,63.0,NaN
109069,110251,Gina Kingsbury,1981-11-26,Uranium City,Saskatchewan,CAN,Canada,173.0,62.0,NaN
109070,110252,Charlie Labonté,1982-10-15,Greenfield Park,Québec,CAN,Canada,175.0,72.0,NaN
117659,119176,Catherine Ward,1987-02-27,Montréal,Québec,CAN,Canada,168.0,67.0,NaN
117691,119212,Haley Irwin,1988-06-06,Thunder Bay,Ontario,CAN,Canada,170.0,78.0,NaN
117757,119286,Marie-Philip Poulin,1991-03-28,Québec City,Québec,CAN,Canada,169.0,72.0,NaN
117771,119300,Meaghan Mikkelson,1985-01-04,Regina,Saskatchewan,CAN,Canada,175.0,67.0,NaN
117816,119353,Rebecca Johnston,1989-09-24,Sudbury,Ontario,CAN,Canada,175.0,67.0,NaN
117837,119377,Shannon Szabados,1986-08-06,Edmonton,Alberta,CAN,Canada,175.0,65.0,NaN
117846,119388,Tessa Bonhomme,1985-07-23,Sudbury,Ontario,CAN,Canada,170.0,63.0,NaN
125146,127490,Mélodie Daoust,1992-01-07,Salaberry-de-Valleyfield,Québec,CAN,Canada,163.0,71.0,NaN
125147,127491,Laura Fortino,1991-01-30,Hamilton,Ontario,CAN,Canada,164.0,62.0,NaN
125148,127492,Brianne Jenner,1991-05-04,Oakville,Ontario,CAN,Canada,175.0,70.0,NaN
125149,127493,Jocelyne Larocque,1988-05-19,NaN,NaN,NaN,Canada,170.0,63.0,NaN
125150,127494,Lauriane Rougeau,1990-04-12,Pointe-Claire,Québec,CAN,Canada,173.0,75.0,NaN
125151,127495,Natalie Spooner,1990-10-17,NaN,NaN,NaN,Canada,178.0,80.0,NaN
125152,127496,Jenn Wakefield,1989-06-15,NaN,NaN,NaN,Canada,178.0,77.0,NaN
125153,127497,Tara Watchorn,1990-05-30,Ajax,Ontario,CAN,Canada,178.0,76.0,NaN
133862,136863,Emily Clark,1995-11-28,Saskatoon,Saskatchewan,CAN,Canada,170.0,61.0,NaN
133863,136864,Ann-Renée Desbiens,1994-04-10,La Malbaie,Québec,CAN,Canada,175.0,73.0,NaN
133864,136865,Renata Fast,1994-10-06,Hamilton,Ontario,CAN,Canada,168.0,65.0,NaN
133866,136867,Sarah Nurse,1995-01-04,Burlington,Ontario,CAN,Canada,175.0,67.0,NaN
133867,136868,Jillian Saulnier,1992-03-07,Halifax,Nova Scotia,CAN,Canada,165.0,66.0,NaN
133868,136869,Laura Stacey,1994-05-05,Mississauga,Ontario,CAN,Canada,178.0,71.0,NaN
133869,136870,Blayre Turnbull,1993-07-15,New Glasgow,Nova Scotia,CAN,Canada,170.0,72.0,NaN
144273,147959,Erin Ambrose,1994-04-30,Newmarket,Ontario,CAN,Canada,165.0,NaN,NaN
144274,147960,Ashton Bell,1999-12-07,Brandon,Manitoba,CAN,Canada,174.0,NaN,NaN
144275,147961,Kristen Campbell,1997-11-30,Brandon,Manitoba,CAN,Canada,175.0,NaN,NaN
144276,147962,Sarah Fillier,2000-06-09,Georgetown,Ontario,CAN,Canada,163.0,NaN,NaN
144277,147963,Emma Maltais,1999-11-04,Cambridge,Massachusetts,USA,Canada,160.0,NaN,NaN
144278,147964,Emerance Maschmeyer,1994-10-05,Fort Saskatchewan,Alberta,CAN,Canada,168.0,NaN,NaN
144279,147965,Jamie Lee Rattray,1992-09-30,Ottawa,Ontario,CAN,Canada,168.0,NaN,NaN
144280,147966,Ella Shelton,1998-01-19,London,Ontario,CAN,Canada,173.0,NaN,NaN
144281,147967,Claire Thompson,1998-01-28,Toronto,Ontario,CAN,Canada,173.0,NaN,NaN
144282,147968,Micah Zandee-Hart,1997-01-13,Victoria,British Columbia,CAN,Canada,NaN,NaN,NaN

**Based on the data set, I accumulated some calculations that can maybe identify some consistences across the players:**

## Average Canada women's hockey player height = 170.64 cm

In [40]:
avg_height = Canada_bios["height_cm"].mean()

In [41]:
avg_height

np.float64(170.64406779661016)

In [43]:
print("Average height:", round(avg_height, 2))

Average height: 170.64

## Average Canada women's hockey player weight = 69.5 kg

In [46]:
avg_weight = Canada_bios["weight_kg"].mean()

In [47]:
avg_weight

np.float64(69.5)

In [50]:
print("Average weight:", avg_weight)

Average weight: 69.5

![](img/ontario.jpg){width=400}

## The number of Canada's women hockey players of where they were born

In [51]:
Canada_bios["born_region"].value_counts()

born_region
Ontario             22
Québec              14
Saskatchewan         7
Manitoba             3
Alberta              3
Nova Scotia          2
Northern Ireland     1
Massachusetts        1
British Columbia     1
Name: count, dtype: int64

![](img/usa_flag.png){width=600}

## **I went ahead and did the same analysis for the past Gold winning U.S. Women's Hockey Teams as well**

In [28]:
US_gold = medals_df.query("event == 'Ice Hockey, Women (Olympic)' and team == 'United States' and medal == 'Gold'")

In [29]:
US_players = US_gold["as"].drop_duplicates()

#### **All of U.S's women hockey players that won gold so far:**

In [30]:
US_players

34735                   Chris Bailey
34737                   Laurie Baker
34739                 Alana Blahoski
34740              Lisa Brown-Miller
34741                      Karyn Bye
34743                  Colleen Coyne
34744                   Sara DeCosta
34746                    Tricia Dunn
34749                  Cammi Granato
34751                     Katie King
34754                 Shelley Looney
34756                       Sue Merz
34758                  A. J. Mleczko
34760                   Tara Mounsey
34762               Vicki Movsessian
34763                Angela Ruggiero
34767               Jenny Schmidgall
34771                  Sarah Tueting
34773                 Gretchen Ulion
34774                   Sandra Whyte
47170                    Gigi Marvin
47181                  Hilary Knight
47215    Jocelyne Lamoureux-Davidson
47239                  Kacey Bellamy
47314                  Meghan Duggan
47337              Monique Lamoureux
53474                  Kendall Coyne
53477                 Brianna Decker
53481                  Amanda Kessel
53487                  Lee Stecklein
58164                   Cayla Barnes
58166                  Hannah Brandt
58168                Dani Cameranesi
58170                  Kali Flanagan
58171                 Nicole Hensley
58173                   Megan Keller
58175                   Sidney Morin
58176                   Kelly Pannek
58178                  Amanda Pelkey
58179                  Emily Pfalzer
58180                  Maddie Rooney
58182                  Haley Skarupa
Name: as, dtype: str

![](img/gold_biting.jpg){width=400}

#### **U.S. women's hockey players that won gold individual bios:**

In [38]:
US_bios = athletes_df[athletes_df["name"].isin(US_players)]

In [39]:
US_bios

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
99653,100452,Chris Bailey,1972-02-05,Marietta,New York,USA,United States,167.0,73.0,NaN
99654,100453,Laurie Baker,1976-11-06,Concord,Massachusetts,USA,United States,170.0,61.0,NaN
99655,100454,Alana Blahoski,1974-04-29,Saint Paul,Minnesota,USA,United States,170.0,57.0,NaN
99656,100455,Lisa Brown-Miller,1966-11-16,Union Lake,Michigan,USA,United States,155.0,57.0,NaN
99657,100456,Karyn Bye,1971-05-18,River Falls,Wisconsin,USA,United States,173.0,75.0,NaN
99658,100457,Colleen Coyne,1971-09-19,Medford,Massachusetts,USA,United States,160.0,59.0,NaN
99659,100458,Sara DeCosta,1977-05-13,Warwick,Rhode Island,USA,United States,178.0,59.0,NaN
99661,100460,Cammi Granato,1971-03-25,Downers Grove,Illinois,USA,United States,170.0,64.0,NaN
99662,100461,Katie King,1975-05-24,Salem,New Hampshire,USA,United States,175.0,77.0,NaN
99663,100462,Shelley Looney,1972-01-21,Brownstown Township,Michigan,USA,United States,165.0,64.0,NaN
99664,100463,Sue Merz,1972-04-10,Greenwich,Connecticut,USA,United States,165.0,66.0,NaN
99665,100464,A. J. Mleczko,1975-06-14,Nantucket,Massachusetts,USA,United States,180.0,73.0,NaN
99666,100465,Tara Mounsey,1978-03-12,Concord,New Hampshire,USA,United States,167.0,68.0,NaN
99667,100466,Vicki Movsessian,1972-11-06,Concord,Massachusetts,USA,United States,165.0,64.0,NaN
99668,100467,Angela Ruggiero,1980-01-03,Panorama City,California,USA,United States,175.0,86.0,NaN
99670,100469,Sarah Tueting,1976-04-26,Winnetka,Illinois,USA,United States,170.0,64.0,NaN
99671,100470,Gretchen Ulion,1972-05-04,Marlborough,Connecticut,USA,United States,157.0,59.0,NaN
99672,100471,Sandra Whyte,1970-08-24,Saugus,Massachusetts,USA,United States,170.0,59.0,NaN
117688,119209,Gigi Marvin,1987-03-07,Bemidji,Minnesota,USA,United States,173.0,73.0,NaN
117693,119215,Hilary Knight,1989-07-12,Palo Alto,California,USA,United States,180.0,79.0,NaN
117715,119240,Jocelyne Lamoureux-Davidson,1989-07-03,Grand Forks,North Dakota,USA,United States,168.0,70.0,NaN
117728,119253,Kacey Bellamy,1987-04-22,Providence,Rhode Island,USA,United States,170.0,66.0,NaN
117772,119301,Meghan Duggan,1987-09-03,Danvers,Massachusetts,USA,United States,178.0,73.0,NaN
117785,119318,Monique Lamoureux,1989-07-03,Grand Forks,North Dakota,USA,United States,168.0,70.0,NaN
126379,128731,Brianna Decker,1991-05-13,Dousman,Wisconsin,USA,United States,163.0,67.0,NaN
126381,128733,Amanda Kessel,1991-08-28,Madison,Wisconsin,USA,United States,165.0,64.0,NaN
126385,128737,Lee Stecklein,1994-04-23,NaN,NaN,NaN,United States,183.0,77.0,NaN
135167,138310,Cayla Barnes,1999-01-07,Eastvale,California,USA,United States,155.0,66.0,NaN
135168,138311,Hannah Brandt,1993-11-27,Maplewood,Minnesota,USA,United States,168.0,68.0,NaN
135169,138312,Dani Cameranesi,1995-06-30,Minneapolis,Minnesota,USA,United States,165.0,67.0,NaN
135170,138313,Kali Flanagan,1995-09-19,Winchester,Massachusetts,USA,United States,163.0,64.0,NaN
135171,138314,Nicole Hensley,1994-06-23,Littleton,Colorado,USA,United States,170.0,70.0,NaN
135172,138315,Megan Keller,1996-05-01,Farmington,Michigan,USA,United States,180.0,73.0,NaN
135173,138316,Sidney Morin,1995-06-06,Edina,Minnesota,USA,United States,165.0,58.0,NaN
135174,138317,Kelly Pannek,1995-12-29,Minneapolis,Minnesota,USA,United States,173.0,75.0,NaN
135175,138318,Amanda Pelkey,1993-05-29,Randolph,Vermont,USA,United States,160.0,61.0,NaN
135176,138319,Emily Pfalzer,1993-06-14,Buffalo,New York,USA,United States,160.0,57.0,NaN
135177,138321,Maddie Rooney,1997-07-07,Andover,Minnesota,USA,United States,165.0,66.0,NaN
135178,138322,Haley Skarupa,1994-01-03,Washington,District of Columbia,USA,United States,168.0,64.0,NaN

## Average U.S. women's hockey player height = 168.51 cm

In [52]:
US_avg_height = US_bios["height_cm"].mean()

In [53]:
US_avg_height

np.float64(168.51282051282053)

In [55]:
print("Average height:", round(US_avg_height, 2))

Average height: 168.51

## Average U.S. women's hockey player weight = 67 kg

In [56]:
US_avg_weight = US_bios["weight_kg"].mean()

In [57]:
US_avg_weight

np.float64(67.0)

In [58]:
print("Average height:", US_avg_weight)

Average height: 67.0

## The number of U.S.'s women hockey players of where they were born

In [59]:
US_bios["born_region"].value_counts()

born_region
Massachusetts           7
Minnesota               7
Wisconsin               3
Michigan                3
California              3
New York                2
Rhode Island            2
Illinois                2
New Hampshire           2
Connecticut             2
North Dakota            2
Colorado                1
Vermont                 1
District of Columbia    1
Name: count, dtype: int64

# Results: Compiled Analysis

**Ideal Canadian Women's Hockey Player:**
- Height: 170.64 cm
- Weight: 69.5 kg
- Dominant Provinces: Ontario & Québec

**Ideal U.S. Women's Hockey Player:**
- Height: 168.51 cm
- Weight: 67 kg
- Dominant States: Massachusetts & Minnesota

**The differences are around 2.1 cm in height and 2.5 kg in weight.**

Dominance and winning cannot generally be attributed to physique alone. Canada has historically dominated the gold medal pool, but it is not like Canadian players are significantly bigger in size than the U.S.. Physical profiles are nearly identical, and sometimes the U.S. captures Gold. So the explanation likely falls elsewhere.

Based on the regional concentrations, it seemed like most of the players on the rosters were primarily from hockey-heavy regions which might be characteristic that defines an ideal hockey player.

![](img/ideal.png){width=400}

From what I gathered from the women's successful hockey players...

# The ideal women's hockey player should be...
- around 169-171 cm tall
- 67-70 kg
- From a hockey-heavy region

![](img/menshockey.jpg){width=600}

## Comparing to Men's Hockey

**I specifically chose Russia and their team as they had an olympic run where they captured gold medals for seven consecutive Olympic Winter Games, which I believed was definite measure of a successful team**

In [63]:
mens_hockey = medals_df[(medals_df["year"] >= 1956) & (medals_df["year"] <= 1978) & (medals_df["event"] == "Ice Hockey, Men (Olympic)") & (medals_df["medal"] == "Gold")]

In [65]:
Russia_players = mens_hockey["as"].drop_duplicates()

#### **All of Russia's men hockey players that won gold so far:**

In [81]:
Russia_players

7979        Boris Aleksandrov
7981     Veniamin Aleksandrov
8021        Aleksandr Almetov
8589           Yevgeny Babich
8591           Sergey Babinov
                 ...
30643           Boris Zaytsev
30644            Oleg Zaytsev
30721         Viktor Zhluktov
30759           Yevgeny Zimin
30800           Viktor Zinger
Name: as, Length: 80, dtype: str

In [67]:
Russia_bios = athletes_df[athletes_df["name"].isin(Russia_players)]

#### **Russia men's hockey players that won gold individual bios:**

In [68]:
Russia_bios

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
20172,20315,Aleksandr Gusev,1955-02-21,Sredneuralsk,Sverdlovsk,RUS,Soviet Union,173.0,74.0,1994-01-01
40026,40334,Vladimir Petrov,1932-04-27,Moskva (Moscow),Moskva,RUS,Soviet Union,NaN,NaN,NaN
82871,83528,Boris Aleksandrov,1955-11-13,Oskemen,Shyrgys Qazaqstan,KAZ,Kazakhstan Soviet Union,168.0,69.0,2002-07-31
82872,83529,Veniamin Aleksandrov,1937-04-18,Moskva (Moscow),Moskva,RUS,Soviet Union,180.0,81.0,1991-11-06
82896,83554,Aleksandr Almetov,1940-01-18,Kyiv,Kyiv,UKR,Soviet Union,178.0,83.0,1992-09-21
...,...,...,...,...,...,...,...,...,...,...
98391,99187,Boris Zaytsev,1937-03-23,Moskva (Moscow),Moskva,RUS,Soviet Union,NaN,NaN,2000-02-24
98392,99188,Oleg Zaytsev,1939-08-04,Moskva (Moscow),Moskva,RUS,Soviet Union,179.0,85.0,1993-03-01
98426,99222,Viktor Zhluktov,1954-01-26,Inta,Respublika Komi,RUS,Soviet Union,190.0,89.0,NaN
98441,99237,Yevgeny Zimin,1947-08-06,Moskva (Moscow),Moskva,RUS,Soviet Union,173.0,82.0,2018-12-28
98451,99247,Viktor Zinger,1941-10-29,Davydovo,Ryazan,RUS,Soviet Union,172.0,70.0,2013-09-24

## Average Russia men's hockey player height = 178.58 cm

In [70]:
Russia_avg_height = Russia_bios["height_cm"].mean()

In [71]:
Russia_avg_height

np.float64(178.57894736842104)

In [72]:
print("Average height:", round(Russia_avg_height, 2))

Average height: 178.58

## Average Russia men's hockey player weight = 80 kg

In [73]:
Russia_avg_weight = Russia_bios["weight_kg"].mean()

In [74]:
Russia_avg_weight

np.float64(80.27397260273973)

In [75]:
print("Average height:", Russia_avg_weight)

Average height: 80.27397260273973

## The number of Russia men's hockey players of where they were born

In [76]:
Russia_bios["born_region"].value_counts()

born_region
Moskva                  35
Minnesota                6
Moskva Oblast            6
Massachusetts            6
Nizhny Novgorod          3
Respublika Komi          2
Tula                     2
Ryazan                   2
Respublika Mordoviya     2
Michigan                 2
Tambov                   1
Omsk                     1
Sverdlovsk               1
Shyrgys Qazaqstan        1
Chelyabinsk              1
Kyiv                     1
Connecticut              1
Kirov                    1
Novosibirsk              1
Indiana                  1
Penza                    1
Krasnodar Kray           1
Smolensk                 1
Khabarovsk Kray          1
Name: count, dtype: int64

# The ideal Russian men's hockey player should be...
- Height: 178.58 cm  
- Weight: 80 kg
- Dominant region: Moskva

Obviously, it would be difficult to compare height and weight of men's hockey player to a women's. But one consistent attribute I see all around between both the men and women seem to be that most winning hockey players are born in hockey-heavy regions where hockey is the culture and main sport.

# The data does not point to a definitive answer of an ideal hockey player. However, it does reveal a consistent pattern: a significant number of Olympic athletes were born in hockey-heavy regions. For Canada, it was Ontario and Quebec. While in the United States, Massachusetts and Minnesota. And for Russia, Moskva. This might suggest that although a competitive athlete has to fit a certain physical frame, winning Gold may be less dependent on individual physical  variations and more about having accessibility to strong developmental programs, competitive youth leagues, and just the culture in general growing up. Maybe accessibility and the system set as a youth hockey player is the most important? A next step in this analysis would be to examine the average age of Olympic players at the time of competition.